### ISSUE TITLE
Use correct shebang

### ISSUE THREAD

**Issue by M-Gregoire** [dietervanhoof/polybar-spotify-controls#1]
Hello,

First of all, thank you for sharing your polybar spotify controls!
In your Python scripts, you use `/bin/python` where it should be something in the form of `/usr/bin/env pythonX` (https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take), which makes your scripts fails in some systems.

If you could use  `/usr/bin/env python3` in `launchlistener.sh` and `#!/usr/bin/env python3` in the two other scripts, that would be awesome.

**Comment by dietervanhoof** [comment]
Thanks for the feedback! I hadn't put any thought into the shebang. Apparently this will break on most systems.
