### ISSUE TITLE
Inter-process messaging needs to be enabled

### ISSUE THREAD

**Issue by febri4n** [dietervanhoof/polybar-spotify-controls#12]
error: Disabling module "spotify" (reason: Inter-process messaging needs to be enabled)
error: Disabling module "playpause" (reason: Inter-process messaging needs to be enabled)

could you help me how to enable Inter-process messaging ?
I already enable ipc in spotify and playhouse module like this

[module/playpause]
type = custom/ipc
**enable-ipc = true**

[module/spotify]
type = custom/ipc
**enable-ipc = true**

is there something wrong ?

**Comment by nileshp87** [comment]
Put in in your bar, not the module

**Comment by dietervanhoof** [comment]
@pseud0nyms did that fix your issue? Sorry about me not replying before.

**Comment by alexfornuto** [comment]
It fixed the same issue for me, FWIW
