### ISSUE TITLE
Working only on one monitor

### ISSUE THREAD

**Issue by welcoMattic** [dietervanhoof/polybar-spotify-controls#5]
Hi! Thanks for your useful script!
I use the same polybar bar on 2 monitors, and your modules work only on one of them.
Do you think is it possible to make them work on the same bar displayed on 2 monitors?

If not, the ugly solution is to duplicate my bar, which I want to avoid ;)

Thanks

**Comment by dietervanhoof** [comment]
Hi welcoMattic,

Thanks for making an issue. Do you use any other components that do work on 2 screens?
I'm not sure how that usually should work and it would be handy to have an example. I guess I'll have to fire up my Linux very soon.

**Comment by dietervanhoof** [comment]
Hi @welcoMattic,

Sorry about the late reply. Do you have other modules that work on the 2 monitors out of the box? You might want to check [this issue](https://github.com/polybar/polybar/issues/763) and make sure you're using the right monitors.

**Comment by dietervanhoof** [comment]
@welcoMattic if you'd like you can retry with the latest version on Github. Otherwise I'll be closing this issue at some point in the future.

**Comment by welcoMattic** [comment]
Hi! I closed this issue because it works! Thanks for the work, and sorry for the delay
