### ISSUE TITLE
py_spotify_listener.py not working

### ISSUE THREAD

**Issue by s0344** [dietervanhoof/polybar-spotify-controls#6]
I created a post in reddit for help and decided to post here too, here is the [link](https://www.reddit.com/r/Polybar/comments/b02hc2/custom_ipc_module_is_not_working/)
Basically, it is an issue with the playpause module

**Comment by dietervanhoof** [comment]
Hi /u/YoloMyth

Sorry about the late reply, I've been quite busy the past few months.
What's the latest status on this? I can see a few comments on the thread but I'm not sure what works now and what doesn't.

I can at least tell you that the output of the `ps aux` isn't what it should be. Only the grep is visible but not the process running the `py_spotify_listener.py`.

**Comment by s0344** [comment]
I have no idea what is wrong but I only know the .py file is not working. Since then, I find out another way to make it happen. Here is the [link](https://github.com/s0344/dotfiles/tree/master/.config/polybar) if you are interested, it is just some script (requires playerctl).

**Comment by dietervanhoof** [comment]
If you run the `py_spotify_listener.py` script manually, does it show any errors? I see you've been able to get the play and pause button to show but the status doesn't seem to work. That's what the `py_spotify_listener.py` script is for. It *should* use that `/tmp/ipc-bottom` file to trigger a 're-render'.

**Comment by s0344** [comment]
It doesn't show any errors at that time and not working at all, therefore, I have no idea what is going wrong.

**Comment by dietervanhoof** [comment]
@s0344 can you verify that you have the symlink set up correctly?
I start up mine with:
```
polybar -c ~/.polybar.conf bottom &                                                                                                                                                                                               
ln -sf /tmp/polybar_mqueue.$! /tmp/ipc-bottom
```
If you'd like to leave this issue as-is, you can close it.

**Comment by mikebyte00** [comment]
I have exactly the same issue. I'm happy to try resolve it.
Thank you s0344, your playerctl scripts work great. It's a shame the ipc stream isn't working as it should.

**Comment by dietervanhoof** [comment]
Try again with the latest version. Make sure to go through the readme again as the symlink part has been removed thanks to the above PR.
