### ISSUE TITLE
Previous and Next modules are still displayed when spotify is closed

### ISSUE THREAD

**Issue by Esya** [dietervanhoof/polybar-spotify-controls#8]
Is there a way to avoid this?

![2019-05-31-021325_343x67_scrot](https://user-images.githubusercontent.com/937179/58672981-b12edb00-8349-11e9-9a30-065f32d0f45c.png)

**Comment by Esya** [comment]
For now I'm doing something dirty :

```
[module/next]
type = custom/script
interval = 10
format = "%{T3}<label>"
format-padding = 5
; Next song icon
exec = pidof spotify >/dev/null && echo ""
format-underline = #1db954
line-size = 1
click-left = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"
```

Changed the interval to 10, added a `pidof spotify` before the echo, it solves it

**Comment by dietervanhoof** [comment]
Good point! Do you think we can do it [this way](https://github.com/polybar/polybar/issues/298)? I feel like this is a pretty clean solution. I'd love to have your opinion on it.

**Comment by dietervanhoof** [comment]
I just tried it out and it seems to work fine for me. I've updated my readme file to reflect the changes in the above pull request. Try it out!

**Comment by dietervanhoof** [comment]
You can always reopen this issue or create a new one if there's still a problem.

**Comment by Esya** [comment]
You're right, it's definitely cleaner than my solution, didn't even know about `exec-if` - What would be great is to also find a way to hide the title and play button **after** spotify has been launched and stopped - not sure how to do this without adding something to the python script that watches the dbus though... Let me know if you have any thoughts. Thanks!
